import React from 'react';

import Navbar from '../components/navbar/navbar';
import Footer from '../components/footer';
import { Metadata } from 'next';
import { Roboto } from 'next/font/google'
import '../styles/App.css';
import ClientSessionProvider from '../providers/sessionProvider';

export const metadata: Metadata = {
    title: "Journal App",
    description: "Generated by create next app",
    viewport: "width=device-width, initial-scale=1",
    icons: {
        icon: "/favicon.ico"
    }
}

const roboto = Roboto({
    weight: ['100','300','400','500','700','900'],
    style: ['normal'],
    subsets:['latin'],
    display: 'swap',
})
   


export default function RootLayout ({children} : {children: React.ReactNode}){
    return (
        <>
            <ClientSessionProvider>
                <html>
                    <body>
                        <Navbar/>
                        {children}
                        <Footer/>
                    </body>
                </html>
            </ClientSessionProvider>
        </>
    );
}