import React,{useEffect} from 'react';
import type { AppProps } from 'next/app';
import Head from 'next/head';
import Link from 'next/link';
import '../styles/App.css';
import Layout from '@/common/layouts/layout';
import { store } from '../redux/store';
import { Provider } from 'react-redux';
import { AuthProvider } from '@/common/context/authContext';

export default function App({ Component, pageProps: {session,...pageProps} }: AppProps) {
  return (
    <>
      <Head>
        <title>Journal App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <Link rel="icon" href="/favicon.ico" />
        <Link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap" rel="stylesheet" />
        <link
                    rel="preload"
                    href="/btn_google_signin_dark_normal_web.png"
                    as="image"
                    />
        <link
                    rel="preload"
                    href="/btn_google_signin_dark_pressed_web.png"
                    as="image"
                    />    
      </Head>
      <AuthProvider>
        <Provider store={store}>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </Provider>
      </AuthProvider>
    </>
  );
}
